production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/data
    read_timeout: 2
    open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/data

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
